import * as stylex from "@stylexjs/stylex";
import { tokens } from "@stylexcn/tokens.stylex";

const SM = "@media (min-width: 40rem)";
const LG = "@media (min-width: 64rem)";

export const chrome = stylex.create({
  header: {
    position: "sticky",
    top: 0,
    zIndex: 40,
    display: "flex",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    height: "4rem",
    paddingInline: "1rem",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens["--border"],
    backgroundColor: "color-mix(in oklab, var(--background) 80%, transparent)",
    backdropFilter: "blur(12px)",
    boxShadow: "none",
  },
  brand: {
    display: "flex",
    alignItems: "baseline",
    gap: "0.5rem",
    textDecorationLine: "none",
    color: tokens["--foreground"],
    fontWeight: 600,
    letterSpacing: "-0.04em",
  },
  brandMark: {
    fontSize: "0.9375rem",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  ghostLink: {
    fontSize: "0.875rem",
    textDecorationLine: "none",
    color: tokens["--muted-foreground"],
    paddingInline: "0.5rem",
    paddingBlock: "0.25rem",
    ":hover": {
      color: tokens["--foreground"],
    },
  },
  layout: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      [LG]: "16rem minmax(0, 1fr)",
    },
    width: "100%",
    minWidth: 0,
    minHeight: "calc(100vh - 4rem)",
  },
  contentColumn: {
    minWidth: 0,
    width: "100%",
  },
  sidebar: {
    display: {
      default: "none",
      [LG]: "block",
    },
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: tokens["--border"],
    padding: "1.25rem 1rem 3rem",
    position: "sticky",
    top: "4rem",
    height: {
      default: "auto",
      [LG]: "calc(100vh - 4rem)",
    },
    overflow: "auto",
  },
  mobileNav: {
    display: {
      default: "block",
      [LG]: "none",
    },
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens["--border"],
    padding: "0.75rem 1rem",
    overflow: "hidden",
  },
  /* display:flex on the list inside closed <details> still generates
     boxes (WebKit/Chromium). Hide the panel unless open. */
  mobileDetails: {
    ":not([open]) > :not(summary)": {
      display: "none",
    },
  },
  navLabel: {
    fontSize: "0.75rem",
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: tokens["--muted-foreground"],
    marginBottom: "0.75rem",
  },
  navSummary: {
    fontSize: "0.75rem",
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: tokens["--muted-foreground"],
    cursor: "pointer",
  },
  navList: {
    listStyleType: "none",
    padding: 0,
    marginTop: "0.75rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
  },
  navLink: {
    display: "block",
    textDecorationLine: "none",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    paddingBlock: "0.375rem",
    paddingInline: "0.5rem",
    borderRadius: tokens["--radius-md"],
    color: tokens["--muted-foreground"],
    ":hover": {
      color: tokens["--foreground"],
      backgroundColor: tokens["--accent"],
    },
  },
  navLinkActive: {
    color: tokens["--foreground"],
    backgroundColor: tokens["--accent"],
    fontWeight: 500,
  },
  main: {
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
    padding: {
      default: "2rem 1rem 4rem",
      [SM]: "2.5rem 2rem 5rem",
    },
    maxWidth: "52rem",
  },
  pageTitle: {
    fontSize: {
      default: "1.875rem",
      [SM]: "2.25rem",
    },
    lineHeight: 1.15,
    letterSpacing: "-0.04em",
    fontWeight: 650,
    marginBottom: "0.75rem",
    overflowWrap: "break-word",
  },
  lead: {
    fontSize: "1rem",
    lineHeight: 1.7,
    color: tokens["--muted-foreground"],
    maxWidth: "40rem",
    marginBottom: 0,
    overflowWrap: "break-word",
  },
  note: {
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: tokens["--muted-foreground"],
    maxWidth: "40rem",
    marginTop: "0.75rem",
    marginBottom: "0.75rem",
  },
  installStack: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    textAlign: "left",
  },
  installRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    overflow: "hidden",
    paddingBlock: "0.35rem",
    paddingInline: "0.55rem 0.35rem",
    borderRadius: tokens["--radius-xl"],
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens["--border"],
    backgroundColor: tokens["--muted"],
  },
  installScroll: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    overflowX: "auto",
    overflowY: "hidden",
    overscrollBehaviorX: "contain",
  },
  installPre: {
    display: "block",
    width: "max-content",
    margin: 0,
    paddingBlock: "0.45rem",
    paddingInline: "0.45rem",
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "0.75rem",
    lineHeight: 1.5,
    color: tokens["--foreground"],
    whiteSpace: "pre",
  },
  installPrompt: {
    color: tokens["--muted-foreground"],
    userSelect: "none",
  },
  installCopy: {
    flexShrink: 0,
  },
  installHint: {
    fontSize: "0.8125rem",
    lineHeight: 1.5,
    color: tokens["--muted-foreground"],
    margin: 0,
    overflowWrap: "break-word",
  },
  sectionTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    letterSpacing: "-0.02em",
    marginTop: "2rem",
    marginBottom: "0.75rem",
  },
  catalogBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginTop: "2rem",
  },
  catalogHeading: {
    marginTop: 0,
    marginBottom: 0,
  },
  demo: {
    minWidth: 0,
    maxWidth: "100%",
    overflowX: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens["--border"],
    borderRadius: tokens["--radius-xl"],
    backgroundColor: tokens["--card"],
    padding: {
      default: "1.25rem",
      [SM]: "1.75rem",
    },
  },
  row: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.75rem",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
    width: "16rem",
    maxWidth: "100%",
  },
  checkRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  muted: {
    fontSize: "0.875rem",
    color: tokens["--muted-foreground"],
  },
  code: {
    display: "block",
    minWidth: 0,
    maxWidth: "100%",
    overflowX: "auto",
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: {
      default: "0.75rem",
      [SM]: "0.8125rem",
    },
    lineHeight: 1.6,
    padding: {
      default: "0.875rem 1rem",
      [SM]: "1rem 1.125rem",
    },
    borderRadius: tokens["--radius-xl"],
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens["--border"],
    backgroundColor: tokens["--muted"],
    color: tokens["--foreground"],
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  hero: {
    padding: {
      default: "3rem 1rem 4rem",
      [SM]: "5rem 2rem 6rem",
    },
    maxWidth: "72rem",
    marginInline: "auto",
  },
  heroGrid: {
    display: "grid",
    gap: "2.5rem",
    gridTemplateColumns: {
      default: "1fr",
      [LG]: "minmax(0, 1fr) 22rem",
    },
    alignItems: "center",
  },
  kicker: {
    fontSize: "0.75rem",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: tokens["--muted-foreground"],
    marginBottom: "0.75rem",
  },
  heroTitle: {
    fontSize: {
      default: "2.25rem",
      [SM]: "3.25rem",
    },
    lineHeight: 1.05,
    letterSpacing: "-0.05em",
    fontWeight: 700,
    marginBottom: "1rem",
  },
  heroCopy: {
    fontSize: "1.0625rem",
    lineHeight: 1.7,
    color: tokens["--muted-foreground"],
    maxWidth: "36rem",
    marginBottom: "1.75rem",
  },
  heroActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
  },
  catalog: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: {
      default: "1fr",
      [SM]: "1fr 1fr",
    },
  },
  catalogCard: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
    textDecorationLine: "none",
    color: tokens["--foreground"],
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens["--border"],
    borderRadius: tokens["--radius-xl"],
    padding: "1rem 1.1rem",
    backgroundColor: tokens["--card"],
    ":hover": {
      backgroundColor: tokens["--accent"],
    },
  },
  catalogName: {
    fontWeight: 600,
    letterSpacing: "-0.02em",
  },
  catalogDesc: {
    fontSize: "0.875rem",
    lineHeight: 1.5,
    color: tokens["--muted-foreground"],
  },
  well: {
    width: "100%",
    maxWidth: "24rem",
  },
  /* Room for Previous/Next, which sit 3rem outside the carousel. */
  carouselStage: {
    display: "flex",
    justifyContent: "center",
    minWidth: 0,
    maxWidth: "100%",
    boxSizing: "border-box",
    paddingInline: {
      default: "2.5rem",
      [SM]: "3rem",
    },
  },
  carouselShell: {
    width: "100%",
    maxWidth: "20rem",
  },
  carouselPad: {
    padding: "0.25rem",
  },
  carouselSlideFace: {
    display: "flex",
    aspectRatio: "1 / 1",
    alignItems: "center",
    justifyContent: "center",
    padding: "1.5rem",
  },
  carouselSlideLabel: {
    fontSize: "2.25rem",
    lineHeight: "2.5rem",
    fontWeight: 600,
  },
  chartWell: {
    width: "100%",
    maxWidth: "20rem",
  },
  chartSize: {
    minHeight: "12.5rem",
    width: "100%",
  },
  /* Contain the primitive: override provider minHeight 100svh and skip
     fixed desktop/mobile sheet layout via collapsible="none". */
  sidebarStage: {
    overflow: "hidden",
    width: "100%",
    height: "18rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens["--border"],
    borderRadius: tokens["--radius-lg"],
  },
  sidebarBrand: {
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    fontWeight: 500,
    paddingInline: "0.5rem",
    paddingBlock: "0.25rem",
  },
  sidebarInsetBar: {
    display: "flex",
    height: "3rem",
    alignItems: "center",
    gap: "0.5rem",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens["--border"],
    paddingInline: "1rem",
    boxSizing: "border-box",
    fontSize: "0.875rem",
    fontWeight: 500,
  },
  commandWell: {
    width: "100%",
    maxWidth: "24rem",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens["--border"],
    borderRadius: tokens["--radius-lg"],
  },
  navMenuStage: {
    minHeight: "12rem",
  },
  navMenuPanel: {
    display: "grid",
    width: "12.5rem",
    gap: "0.25rem",
    margin: 0,
    padding: 0,
    listStyleType: "none",
  },
  wideWell: {
    width: "100%",
    maxWidth: "32rem",
  },
  skeletonBar: {
    width: "15.625rem",
    height: "1rem",
  },
  skeletonCircle: {
    width: "2.5rem",
    height: "2.5rem",
  },
  separatorH: {
    width: "16rem",
  },
  separatorV: {
    height: "6rem",
    width: "3rem",
    display: "flex",
    justifyContent: "center",
  },
  aspectFill: {
    width: "100%",
    height: "100%",
    backgroundColor: tokens["--muted"],
  },
  scrollV: {
    width: "12rem",
    height: "8rem",
  },
  scrollH: {
    width: "16rem",
    height: "6rem",
  },
  scrollList: {
    padding: "1rem",
  },
  scrollItem: {
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    paddingBlock: "0.25rem",
  },
  scrollStrip: {
    display: "flex",
    width: "max-content",
    gap: "0.75rem",
    padding: "1rem",
  },
  scrollBlock: {
    width: "5rem",
    height: "3.5rem",
    flexShrink: 0,
    borderRadius: "0.375rem",
    backgroundColor: tokens["--muted"],
  },
  resizableH: {
    width: "100%",
    maxWidth: "24rem",
    height: "8rem",
  },
  resizableV: {
    width: "16rem",
    height: "12rem",
  },
  resizableFill: {
    height: "100%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: tokens["--muted"],
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: tokens["--border"],
    fontSize: "0.875rem",
  },
  contextTrigger: {
    display: "flex",
    height: "9.375rem",
    width: "18.75rem",
    maxWidth: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: tokens["--radius-md"],
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: tokens["--border"],
    fontSize: "0.875rem",
    color: tokens["--muted-foreground"],
  },
  tableAmount: {
    textAlign: "right",
  },
  tableStrong: {
    fontWeight: 500,
  },
});
